
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Dish` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Dish
 * 
 */
export type DishModel = runtime.Types.Result.DefaultSelection<Prisma.$DishPayload>

export type AggregateDish = {
  _count: DishCountAggregateOutputType | null
  _avg: DishAvgAggregateOutputType | null
  _sum: DishSumAggregateOutputType | null
  _min: DishMinAggregateOutputType | null
  _max: DishMaxAggregateOutputType | null
}

export type DishAvgAggregateOutputType = {
  sn: number | null
}

export type DishSumAggregateOutputType = {
  sn: number | null
}

export type DishMinAggregateOutputType = {
  id: string | null
  title: string | null
  kind_id: string | null
  sn: number | null
}

export type DishMaxAggregateOutputType = {
  id: string | null
  title: string | null
  kind_id: string | null
  sn: number | null
}

export type DishCountAggregateOutputType = {
  id: number
  title: number
  kind_id: number
  sn: number
  _all: number
}


export type DishAvgAggregateInputType = {
  sn?: true
}

export type DishSumAggregateInputType = {
  sn?: true
}

export type DishMinAggregateInputType = {
  id?: true
  title?: true
  kind_id?: true
  sn?: true
}

export type DishMaxAggregateInputType = {
  id?: true
  title?: true
  kind_id?: true
  sn?: true
}

export type DishCountAggregateInputType = {
  id?: true
  title?: true
  kind_id?: true
  sn?: true
  _all?: true
}

export type DishAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Dish to aggregate.
   */
  where?: Prisma.DishWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dishes to fetch.
   */
  orderBy?: Prisma.DishOrderByWithRelationInput | Prisma.DishOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DishWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dishes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dishes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Dishes
  **/
  _count?: true | DishCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DishAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DishSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DishMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DishMaxAggregateInputType
}

export type GetDishAggregateType<T extends DishAggregateArgs> = {
      [P in keyof T & keyof AggregateDish]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDish[P]>
    : Prisma.GetScalarType<T[P], AggregateDish[P]>
}




export type DishGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DishWhereInput
  orderBy?: Prisma.DishOrderByWithAggregationInput | Prisma.DishOrderByWithAggregationInput[]
  by: Prisma.DishScalarFieldEnum[] | Prisma.DishScalarFieldEnum
  having?: Prisma.DishScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DishCountAggregateInputType | true
  _avg?: DishAvgAggregateInputType
  _sum?: DishSumAggregateInputType
  _min?: DishMinAggregateInputType
  _max?: DishMaxAggregateInputType
}

export type DishGroupByOutputType = {
  id: string
  title: string
  kind_id: string
  sn: number
  _count: DishCountAggregateOutputType | null
  _avg: DishAvgAggregateOutputType | null
  _sum: DishSumAggregateOutputType | null
  _min: DishMinAggregateOutputType | null
  _max: DishMaxAggregateOutputType | null
}

export type GetDishGroupByPayload<T extends DishGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DishGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DishGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DishGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DishGroupByOutputType[P]>
      }
    >
  >



export type DishWhereInput = {
  AND?: Prisma.DishWhereInput | Prisma.DishWhereInput[]
  OR?: Prisma.DishWhereInput[]
  NOT?: Prisma.DishWhereInput | Prisma.DishWhereInput[]
  id?: Prisma.StringFilter<"Dish"> | string
  title?: Prisma.StringFilter<"Dish"> | string
  kind_id?: Prisma.StringFilter<"Dish"> | string
  sn?: Prisma.IntFilter<"Dish"> | number
}

export type DishOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  kind_id?: Prisma.SortOrder
  sn?: Prisma.SortOrder
}

export type DishWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DishWhereInput | Prisma.DishWhereInput[]
  OR?: Prisma.DishWhereInput[]
  NOT?: Prisma.DishWhereInput | Prisma.DishWhereInput[]
  title?: Prisma.StringFilter<"Dish"> | string
  kind_id?: Prisma.StringFilter<"Dish"> | string
  sn?: Prisma.IntFilter<"Dish"> | number
}, "id">

export type DishOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  kind_id?: Prisma.SortOrder
  sn?: Prisma.SortOrder
  _count?: Prisma.DishCountOrderByAggregateInput
  _avg?: Prisma.DishAvgOrderByAggregateInput
  _max?: Prisma.DishMaxOrderByAggregateInput
  _min?: Prisma.DishMinOrderByAggregateInput
  _sum?: Prisma.DishSumOrderByAggregateInput
}

export type DishScalarWhereWithAggregatesInput = {
  AND?: Prisma.DishScalarWhereWithAggregatesInput | Prisma.DishScalarWhereWithAggregatesInput[]
  OR?: Prisma.DishScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DishScalarWhereWithAggregatesInput | Prisma.DishScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Dish"> | string
  title?: Prisma.StringWithAggregatesFilter<"Dish"> | string
  kind_id?: Prisma.StringWithAggregatesFilter<"Dish"> | string
  sn?: Prisma.IntWithAggregatesFilter<"Dish"> | number
}

export type DishCreateInput = {
  id?: string
  title: string
  kind_id: string
  sn?: number
}

export type DishUncheckedCreateInput = {
  id?: string
  title: string
  kind_id: string
  sn?: number
}

export type DishUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  kind_id?: Prisma.StringFieldUpdateOperationsInput | string
  sn?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DishUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  kind_id?: Prisma.StringFieldUpdateOperationsInput | string
  sn?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DishCreateManyInput = {
  id?: string
  title: string
  kind_id: string
  sn?: number
}

export type DishUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  kind_id?: Prisma.StringFieldUpdateOperationsInput | string
  sn?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DishUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  kind_id?: Prisma.StringFieldUpdateOperationsInput | string
  sn?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DishCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  kind_id?: Prisma.SortOrder
  sn?: Prisma.SortOrder
}

export type DishAvgOrderByAggregateInput = {
  sn?: Prisma.SortOrder
}

export type DishMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  kind_id?: Prisma.SortOrder
  sn?: Prisma.SortOrder
}

export type DishMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  kind_id?: Prisma.SortOrder
  sn?: Prisma.SortOrder
}

export type DishSumOrderByAggregateInput = {
  sn?: Prisma.SortOrder
}



export type DishSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  kind_id?: boolean
  sn?: boolean
}, ExtArgs["result"]["dish"]>

export type DishSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  kind_id?: boolean
  sn?: boolean
}, ExtArgs["result"]["dish"]>

export type DishSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  kind_id?: boolean
  sn?: boolean
}, ExtArgs["result"]["dish"]>

export type DishSelectScalar = {
  id?: boolean
  title?: boolean
  kind_id?: boolean
  sn?: boolean
}

export type DishOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "kind_id" | "sn", ExtArgs["result"]["dish"]>

export type $DishPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Dish"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    kind_id: string
    sn: number
  }, ExtArgs["result"]["dish"]>
  composites: {}
}

export type DishGetPayload<S extends boolean | null | undefined | DishDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DishPayload, S>

export type DishCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DishFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DishCountAggregateInputType | true
  }

export interface DishDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Dish'], meta: { name: 'Dish' } }
  /**
   * Find zero or one Dish that matches the filter.
   * @param {DishFindUniqueArgs} args - Arguments to find a Dish
   * @example
   * // Get one Dish
   * const dish = await prisma.dish.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DishFindUniqueArgs>(args: Prisma.SelectSubset<T, DishFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DishClient<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dish that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DishFindUniqueOrThrowArgs} args - Arguments to find a Dish
   * @example
   * // Get one Dish
   * const dish = await prisma.dish.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DishFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DishFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DishClient<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dish that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DishFindFirstArgs} args - Arguments to find a Dish
   * @example
   * // Get one Dish
   * const dish = await prisma.dish.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DishFindFirstArgs>(args?: Prisma.SelectSubset<T, DishFindFirstArgs<ExtArgs>>): Prisma.Prisma__DishClient<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dish that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DishFindFirstOrThrowArgs} args - Arguments to find a Dish
   * @example
   * // Get one Dish
   * const dish = await prisma.dish.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DishFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DishFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DishClient<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Dishes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DishFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Dishes
   * const dishes = await prisma.dish.findMany()
   * 
   * // Get first 10 Dishes
   * const dishes = await prisma.dish.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dishWithIdOnly = await prisma.dish.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DishFindManyArgs>(args?: Prisma.SelectSubset<T, DishFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dish.
   * @param {DishCreateArgs} args - Arguments to create a Dish.
   * @example
   * // Create one Dish
   * const Dish = await prisma.dish.create({
   *   data: {
   *     // ... data to create a Dish
   *   }
   * })
   * 
   */
  create<T extends DishCreateArgs>(args: Prisma.SelectSubset<T, DishCreateArgs<ExtArgs>>): Prisma.Prisma__DishClient<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Dishes.
   * @param {DishCreateManyArgs} args - Arguments to create many Dishes.
   * @example
   * // Create many Dishes
   * const dish = await prisma.dish.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DishCreateManyArgs>(args?: Prisma.SelectSubset<T, DishCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Dishes and returns the data saved in the database.
   * @param {DishCreateManyAndReturnArgs} args - Arguments to create many Dishes.
   * @example
   * // Create many Dishes
   * const dish = await prisma.dish.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Dishes and only return the `id`
   * const dishWithIdOnly = await prisma.dish.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DishCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DishCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Dish.
   * @param {DishDeleteArgs} args - Arguments to delete one Dish.
   * @example
   * // Delete one Dish
   * const Dish = await prisma.dish.delete({
   *   where: {
   *     // ... filter to delete one Dish
   *   }
   * })
   * 
   */
  delete<T extends DishDeleteArgs>(args: Prisma.SelectSubset<T, DishDeleteArgs<ExtArgs>>): Prisma.Prisma__DishClient<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dish.
   * @param {DishUpdateArgs} args - Arguments to update one Dish.
   * @example
   * // Update one Dish
   * const dish = await prisma.dish.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DishUpdateArgs>(args: Prisma.SelectSubset<T, DishUpdateArgs<ExtArgs>>): Prisma.Prisma__DishClient<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Dishes.
   * @param {DishDeleteManyArgs} args - Arguments to filter Dishes to delete.
   * @example
   * // Delete a few Dishes
   * const { count } = await prisma.dish.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DishDeleteManyArgs>(args?: Prisma.SelectSubset<T, DishDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dishes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DishUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Dishes
   * const dish = await prisma.dish.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DishUpdateManyArgs>(args: Prisma.SelectSubset<T, DishUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dishes and returns the data updated in the database.
   * @param {DishUpdateManyAndReturnArgs} args - Arguments to update many Dishes.
   * @example
   * // Update many Dishes
   * const dish = await prisma.dish.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Dishes and only return the `id`
   * const dishWithIdOnly = await prisma.dish.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DishUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DishUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Dish.
   * @param {DishUpsertArgs} args - Arguments to update or create a Dish.
   * @example
   * // Update or create a Dish
   * const dish = await prisma.dish.upsert({
   *   create: {
   *     // ... data to create a Dish
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dish we want to update
   *   }
   * })
   */
  upsert<T extends DishUpsertArgs>(args: Prisma.SelectSubset<T, DishUpsertArgs<ExtArgs>>): Prisma.Prisma__DishClient<runtime.Types.Result.GetResult<Prisma.$DishPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Dishes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DishCountArgs} args - Arguments to filter Dishes to count.
   * @example
   * // Count the number of Dishes
   * const count = await prisma.dish.count({
   *   where: {
   *     // ... the filter for the Dishes we want to count
   *   }
   * })
  **/
  count<T extends DishCountArgs>(
    args?: Prisma.Subset<T, DishCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DishCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dish.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DishAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DishAggregateArgs>(args: Prisma.Subset<T, DishAggregateArgs>): Prisma.PrismaPromise<GetDishAggregateType<T>>

  /**
   * Group by Dish.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DishGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DishGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DishGroupByArgs['orderBy'] }
      : { orderBy?: DishGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DishGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDishGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Dish model
 */
readonly fields: DishFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Dish.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DishClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Dish model
 */
export interface DishFieldRefs {
  readonly id: Prisma.FieldRef<"Dish", 'String'>
  readonly title: Prisma.FieldRef<"Dish", 'String'>
  readonly kind_id: Prisma.FieldRef<"Dish", 'String'>
  readonly sn: Prisma.FieldRef<"Dish", 'Int'>
}
    

// Custom InputTypes
/**
 * Dish findUnique
 */
export type DishFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * Filter, which Dish to fetch.
   */
  where: Prisma.DishWhereUniqueInput
}

/**
 * Dish findUniqueOrThrow
 */
export type DishFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * Filter, which Dish to fetch.
   */
  where: Prisma.DishWhereUniqueInput
}

/**
 * Dish findFirst
 */
export type DishFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * Filter, which Dish to fetch.
   */
  where?: Prisma.DishWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dishes to fetch.
   */
  orderBy?: Prisma.DishOrderByWithRelationInput | Prisma.DishOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Dishes.
   */
  cursor?: Prisma.DishWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dishes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dishes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Dishes.
   */
  distinct?: Prisma.DishScalarFieldEnum | Prisma.DishScalarFieldEnum[]
}

/**
 * Dish findFirstOrThrow
 */
export type DishFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * Filter, which Dish to fetch.
   */
  where?: Prisma.DishWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dishes to fetch.
   */
  orderBy?: Prisma.DishOrderByWithRelationInput | Prisma.DishOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Dishes.
   */
  cursor?: Prisma.DishWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dishes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dishes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Dishes.
   */
  distinct?: Prisma.DishScalarFieldEnum | Prisma.DishScalarFieldEnum[]
}

/**
 * Dish findMany
 */
export type DishFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * Filter, which Dishes to fetch.
   */
  where?: Prisma.DishWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dishes to fetch.
   */
  orderBy?: Prisma.DishOrderByWithRelationInput | Prisma.DishOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Dishes.
   */
  cursor?: Prisma.DishWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dishes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dishes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Dishes.
   */
  distinct?: Prisma.DishScalarFieldEnum | Prisma.DishScalarFieldEnum[]
}

/**
 * Dish create
 */
export type DishCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * The data needed to create a Dish.
   */
  data: Prisma.XOR<Prisma.DishCreateInput, Prisma.DishUncheckedCreateInput>
}

/**
 * Dish createMany
 */
export type DishCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Dishes.
   */
  data: Prisma.DishCreateManyInput | Prisma.DishCreateManyInput[]
}

/**
 * Dish createManyAndReturn
 */
export type DishCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * The data used to create many Dishes.
   */
  data: Prisma.DishCreateManyInput | Prisma.DishCreateManyInput[]
}

/**
 * Dish update
 */
export type DishUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * The data needed to update a Dish.
   */
  data: Prisma.XOR<Prisma.DishUpdateInput, Prisma.DishUncheckedUpdateInput>
  /**
   * Choose, which Dish to update.
   */
  where: Prisma.DishWhereUniqueInput
}

/**
 * Dish updateMany
 */
export type DishUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Dishes.
   */
  data: Prisma.XOR<Prisma.DishUpdateManyMutationInput, Prisma.DishUncheckedUpdateManyInput>
  /**
   * Filter which Dishes to update
   */
  where?: Prisma.DishWhereInput
  /**
   * Limit how many Dishes to update.
   */
  limit?: number
}

/**
 * Dish updateManyAndReturn
 */
export type DishUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * The data used to update Dishes.
   */
  data: Prisma.XOR<Prisma.DishUpdateManyMutationInput, Prisma.DishUncheckedUpdateManyInput>
  /**
   * Filter which Dishes to update
   */
  where?: Prisma.DishWhereInput
  /**
   * Limit how many Dishes to update.
   */
  limit?: number
}

/**
 * Dish upsert
 */
export type DishUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * The filter to search for the Dish to update in case it exists.
   */
  where: Prisma.DishWhereUniqueInput
  /**
   * In case the Dish found by the `where` argument doesn't exist, create a new Dish with this data.
   */
  create: Prisma.XOR<Prisma.DishCreateInput, Prisma.DishUncheckedCreateInput>
  /**
   * In case the Dish was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DishUpdateInput, Prisma.DishUncheckedUpdateInput>
}

/**
 * Dish delete
 */
export type DishDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
  /**
   * Filter which Dish to delete.
   */
  where: Prisma.DishWhereUniqueInput
}

/**
 * Dish deleteMany
 */
export type DishDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Dishes to delete
   */
  where?: Prisma.DishWhereInput
  /**
   * Limit how many Dishes to delete.
   */
  limit?: number
}

/**
 * Dish without action
 */
export type DishDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dish
   */
  select?: Prisma.DishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dish
   */
  omit?: Prisma.DishOmit<ExtArgs> | null
}
