
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Kind` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Kind
 * 
 */
export type KindModel = runtime.Types.Result.DefaultSelection<Prisma.$KindPayload>

export type AggregateKind = {
  _count: KindCountAggregateOutputType | null
  _avg: KindAvgAggregateOutputType | null
  _sum: KindSumAggregateOutputType | null
  _min: KindMinAggregateOutputType | null
  _max: KindMaxAggregateOutputType | null
}

export type KindAvgAggregateOutputType = {
  sn: number | null
}

export type KindSumAggregateOutputType = {
  sn: number | null
}

export type KindMinAggregateOutputType = {
  id: string | null
  title: string | null
  sn: number | null
}

export type KindMaxAggregateOutputType = {
  id: string | null
  title: string | null
  sn: number | null
}

export type KindCountAggregateOutputType = {
  id: number
  title: number
  sn: number
  _all: number
}


export type KindAvgAggregateInputType = {
  sn?: true
}

export type KindSumAggregateInputType = {
  sn?: true
}

export type KindMinAggregateInputType = {
  id?: true
  title?: true
  sn?: true
}

export type KindMaxAggregateInputType = {
  id?: true
  title?: true
  sn?: true
}

export type KindCountAggregateInputType = {
  id?: true
  title?: true
  sn?: true
  _all?: true
}

export type KindAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Kind to aggregate.
   */
  where?: Prisma.KindWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kinds to fetch.
   */
  orderBy?: Prisma.KindOrderByWithRelationInput | Prisma.KindOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KindWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kinds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kinds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Kinds
  **/
  _count?: true | KindCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: KindAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: KindSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KindMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KindMaxAggregateInputType
}

export type GetKindAggregateType<T extends KindAggregateArgs> = {
      [P in keyof T & keyof AggregateKind]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKind[P]>
    : Prisma.GetScalarType<T[P], AggregateKind[P]>
}




export type KindGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KindWhereInput
  orderBy?: Prisma.KindOrderByWithAggregationInput | Prisma.KindOrderByWithAggregationInput[]
  by: Prisma.KindScalarFieldEnum[] | Prisma.KindScalarFieldEnum
  having?: Prisma.KindScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KindCountAggregateInputType | true
  _avg?: KindAvgAggregateInputType
  _sum?: KindSumAggregateInputType
  _min?: KindMinAggregateInputType
  _max?: KindMaxAggregateInputType
}

export type KindGroupByOutputType = {
  id: string
  title: string
  sn: number
  _count: KindCountAggregateOutputType | null
  _avg: KindAvgAggregateOutputType | null
  _sum: KindSumAggregateOutputType | null
  _min: KindMinAggregateOutputType | null
  _max: KindMaxAggregateOutputType | null
}

export type GetKindGroupByPayload<T extends KindGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KindGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KindGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KindGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KindGroupByOutputType[P]>
      }
    >
  >



export type KindWhereInput = {
  AND?: Prisma.KindWhereInput | Prisma.KindWhereInput[]
  OR?: Prisma.KindWhereInput[]
  NOT?: Prisma.KindWhereInput | Prisma.KindWhereInput[]
  id?: Prisma.StringFilter<"Kind"> | string
  title?: Prisma.StringFilter<"Kind"> | string
  sn?: Prisma.IntFilter<"Kind"> | number
}

export type KindOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sn?: Prisma.SortOrder
}

export type KindWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.KindWhereInput | Prisma.KindWhereInput[]
  OR?: Prisma.KindWhereInput[]
  NOT?: Prisma.KindWhereInput | Prisma.KindWhereInput[]
  title?: Prisma.StringFilter<"Kind"> | string
  sn?: Prisma.IntFilter<"Kind"> | number
}, "id">

export type KindOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sn?: Prisma.SortOrder
  _count?: Prisma.KindCountOrderByAggregateInput
  _avg?: Prisma.KindAvgOrderByAggregateInput
  _max?: Prisma.KindMaxOrderByAggregateInput
  _min?: Prisma.KindMinOrderByAggregateInput
  _sum?: Prisma.KindSumOrderByAggregateInput
}

export type KindScalarWhereWithAggregatesInput = {
  AND?: Prisma.KindScalarWhereWithAggregatesInput | Prisma.KindScalarWhereWithAggregatesInput[]
  OR?: Prisma.KindScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KindScalarWhereWithAggregatesInput | Prisma.KindScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Kind"> | string
  title?: Prisma.StringWithAggregatesFilter<"Kind"> | string
  sn?: Prisma.IntWithAggregatesFilter<"Kind"> | number
}

export type KindCreateInput = {
  id?: string
  title: string
  sn?: number
}

export type KindUncheckedCreateInput = {
  id?: string
  title: string
  sn?: number
}

export type KindUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sn?: Prisma.IntFieldUpdateOperationsInput | number
}

export type KindUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sn?: Prisma.IntFieldUpdateOperationsInput | number
}

export type KindCreateManyInput = {
  id?: string
  title: string
  sn?: number
}

export type KindUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sn?: Prisma.IntFieldUpdateOperationsInput | number
}

export type KindUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  sn?: Prisma.IntFieldUpdateOperationsInput | number
}

export type KindCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sn?: Prisma.SortOrder
}

export type KindAvgOrderByAggregateInput = {
  sn?: Prisma.SortOrder
}

export type KindMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sn?: Prisma.SortOrder
}

export type KindMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sn?: Prisma.SortOrder
}

export type KindSumOrderByAggregateInput = {
  sn?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type KindSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  sn?: boolean
}, ExtArgs["result"]["kind"]>

export type KindSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  sn?: boolean
}, ExtArgs["result"]["kind"]>

export type KindSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  sn?: boolean
}, ExtArgs["result"]["kind"]>

export type KindSelectScalar = {
  id?: boolean
  title?: boolean
  sn?: boolean
}

export type KindOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "sn", ExtArgs["result"]["kind"]>

export type $KindPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Kind"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    sn: number
  }, ExtArgs["result"]["kind"]>
  composites: {}
}

export type KindGetPayload<S extends boolean | null | undefined | KindDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KindPayload, S>

export type KindCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KindFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KindCountAggregateInputType | true
  }

export interface KindDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Kind'], meta: { name: 'Kind' } }
  /**
   * Find zero or one Kind that matches the filter.
   * @param {KindFindUniqueArgs} args - Arguments to find a Kind
   * @example
   * // Get one Kind
   * const kind = await prisma.kind.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KindFindUniqueArgs>(args: Prisma.SelectSubset<T, KindFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KindClient<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Kind that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KindFindUniqueOrThrowArgs} args - Arguments to find a Kind
   * @example
   * // Get one Kind
   * const kind = await prisma.kind.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KindFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KindFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KindClient<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Kind that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KindFindFirstArgs} args - Arguments to find a Kind
   * @example
   * // Get one Kind
   * const kind = await prisma.kind.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KindFindFirstArgs>(args?: Prisma.SelectSubset<T, KindFindFirstArgs<ExtArgs>>): Prisma.Prisma__KindClient<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Kind that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KindFindFirstOrThrowArgs} args - Arguments to find a Kind
   * @example
   * // Get one Kind
   * const kind = await prisma.kind.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KindFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KindFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KindClient<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Kinds that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KindFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Kinds
   * const kinds = await prisma.kind.findMany()
   * 
   * // Get first 10 Kinds
   * const kinds = await prisma.kind.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kindWithIdOnly = await prisma.kind.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KindFindManyArgs>(args?: Prisma.SelectSubset<T, KindFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Kind.
   * @param {KindCreateArgs} args - Arguments to create a Kind.
   * @example
   * // Create one Kind
   * const Kind = await prisma.kind.create({
   *   data: {
   *     // ... data to create a Kind
   *   }
   * })
   * 
   */
  create<T extends KindCreateArgs>(args: Prisma.SelectSubset<T, KindCreateArgs<ExtArgs>>): Prisma.Prisma__KindClient<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Kinds.
   * @param {KindCreateManyArgs} args - Arguments to create many Kinds.
   * @example
   * // Create many Kinds
   * const kind = await prisma.kind.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KindCreateManyArgs>(args?: Prisma.SelectSubset<T, KindCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Kinds and returns the data saved in the database.
   * @param {KindCreateManyAndReturnArgs} args - Arguments to create many Kinds.
   * @example
   * // Create many Kinds
   * const kind = await prisma.kind.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Kinds and only return the `id`
   * const kindWithIdOnly = await prisma.kind.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KindCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KindCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Kind.
   * @param {KindDeleteArgs} args - Arguments to delete one Kind.
   * @example
   * // Delete one Kind
   * const Kind = await prisma.kind.delete({
   *   where: {
   *     // ... filter to delete one Kind
   *   }
   * })
   * 
   */
  delete<T extends KindDeleteArgs>(args: Prisma.SelectSubset<T, KindDeleteArgs<ExtArgs>>): Prisma.Prisma__KindClient<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Kind.
   * @param {KindUpdateArgs} args - Arguments to update one Kind.
   * @example
   * // Update one Kind
   * const kind = await prisma.kind.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KindUpdateArgs>(args: Prisma.SelectSubset<T, KindUpdateArgs<ExtArgs>>): Prisma.Prisma__KindClient<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Kinds.
   * @param {KindDeleteManyArgs} args - Arguments to filter Kinds to delete.
   * @example
   * // Delete a few Kinds
   * const { count } = await prisma.kind.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KindDeleteManyArgs>(args?: Prisma.SelectSubset<T, KindDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Kinds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KindUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Kinds
   * const kind = await prisma.kind.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KindUpdateManyArgs>(args: Prisma.SelectSubset<T, KindUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Kinds and returns the data updated in the database.
   * @param {KindUpdateManyAndReturnArgs} args - Arguments to update many Kinds.
   * @example
   * // Update many Kinds
   * const kind = await prisma.kind.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Kinds and only return the `id`
   * const kindWithIdOnly = await prisma.kind.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KindUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KindUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Kind.
   * @param {KindUpsertArgs} args - Arguments to update or create a Kind.
   * @example
   * // Update or create a Kind
   * const kind = await prisma.kind.upsert({
   *   create: {
   *     // ... data to create a Kind
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Kind we want to update
   *   }
   * })
   */
  upsert<T extends KindUpsertArgs>(args: Prisma.SelectSubset<T, KindUpsertArgs<ExtArgs>>): Prisma.Prisma__KindClient<runtime.Types.Result.GetResult<Prisma.$KindPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Kinds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KindCountArgs} args - Arguments to filter Kinds to count.
   * @example
   * // Count the number of Kinds
   * const count = await prisma.kind.count({
   *   where: {
   *     // ... the filter for the Kinds we want to count
   *   }
   * })
  **/
  count<T extends KindCountArgs>(
    args?: Prisma.Subset<T, KindCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KindCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Kind.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KindAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KindAggregateArgs>(args: Prisma.Subset<T, KindAggregateArgs>): Prisma.PrismaPromise<GetKindAggregateType<T>>

  /**
   * Group by Kind.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KindGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KindGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KindGroupByArgs['orderBy'] }
      : { orderBy?: KindGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KindGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKindGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Kind model
 */
readonly fields: KindFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Kind.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KindClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Kind model
 */
export interface KindFieldRefs {
  readonly id: Prisma.FieldRef<"Kind", 'String'>
  readonly title: Prisma.FieldRef<"Kind", 'String'>
  readonly sn: Prisma.FieldRef<"Kind", 'Int'>
}
    

// Custom InputTypes
/**
 * Kind findUnique
 */
export type KindFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * Filter, which Kind to fetch.
   */
  where: Prisma.KindWhereUniqueInput
}

/**
 * Kind findUniqueOrThrow
 */
export type KindFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * Filter, which Kind to fetch.
   */
  where: Prisma.KindWhereUniqueInput
}

/**
 * Kind findFirst
 */
export type KindFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * Filter, which Kind to fetch.
   */
  where?: Prisma.KindWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kinds to fetch.
   */
  orderBy?: Prisma.KindOrderByWithRelationInput | Prisma.KindOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Kinds.
   */
  cursor?: Prisma.KindWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kinds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kinds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Kinds.
   */
  distinct?: Prisma.KindScalarFieldEnum | Prisma.KindScalarFieldEnum[]
}

/**
 * Kind findFirstOrThrow
 */
export type KindFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * Filter, which Kind to fetch.
   */
  where?: Prisma.KindWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kinds to fetch.
   */
  orderBy?: Prisma.KindOrderByWithRelationInput | Prisma.KindOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Kinds.
   */
  cursor?: Prisma.KindWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kinds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kinds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Kinds.
   */
  distinct?: Prisma.KindScalarFieldEnum | Prisma.KindScalarFieldEnum[]
}

/**
 * Kind findMany
 */
export type KindFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * Filter, which Kinds to fetch.
   */
  where?: Prisma.KindWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kinds to fetch.
   */
  orderBy?: Prisma.KindOrderByWithRelationInput | Prisma.KindOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Kinds.
   */
  cursor?: Prisma.KindWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kinds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kinds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Kinds.
   */
  distinct?: Prisma.KindScalarFieldEnum | Prisma.KindScalarFieldEnum[]
}

/**
 * Kind create
 */
export type KindCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * The data needed to create a Kind.
   */
  data: Prisma.XOR<Prisma.KindCreateInput, Prisma.KindUncheckedCreateInput>
}

/**
 * Kind createMany
 */
export type KindCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Kinds.
   */
  data: Prisma.KindCreateManyInput | Prisma.KindCreateManyInput[]
}

/**
 * Kind createManyAndReturn
 */
export type KindCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * The data used to create many Kinds.
   */
  data: Prisma.KindCreateManyInput | Prisma.KindCreateManyInput[]
}

/**
 * Kind update
 */
export type KindUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * The data needed to update a Kind.
   */
  data: Prisma.XOR<Prisma.KindUpdateInput, Prisma.KindUncheckedUpdateInput>
  /**
   * Choose, which Kind to update.
   */
  where: Prisma.KindWhereUniqueInput
}

/**
 * Kind updateMany
 */
export type KindUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Kinds.
   */
  data: Prisma.XOR<Prisma.KindUpdateManyMutationInput, Prisma.KindUncheckedUpdateManyInput>
  /**
   * Filter which Kinds to update
   */
  where?: Prisma.KindWhereInput
  /**
   * Limit how many Kinds to update.
   */
  limit?: number
}

/**
 * Kind updateManyAndReturn
 */
export type KindUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * The data used to update Kinds.
   */
  data: Prisma.XOR<Prisma.KindUpdateManyMutationInput, Prisma.KindUncheckedUpdateManyInput>
  /**
   * Filter which Kinds to update
   */
  where?: Prisma.KindWhereInput
  /**
   * Limit how many Kinds to update.
   */
  limit?: number
}

/**
 * Kind upsert
 */
export type KindUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * The filter to search for the Kind to update in case it exists.
   */
  where: Prisma.KindWhereUniqueInput
  /**
   * In case the Kind found by the `where` argument doesn't exist, create a new Kind with this data.
   */
  create: Prisma.XOR<Prisma.KindCreateInput, Prisma.KindUncheckedCreateInput>
  /**
   * In case the Kind was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KindUpdateInput, Prisma.KindUncheckedUpdateInput>
}

/**
 * Kind delete
 */
export type KindDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
  /**
   * Filter which Kind to delete.
   */
  where: Prisma.KindWhereUniqueInput
}

/**
 * Kind deleteMany
 */
export type KindDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Kinds to delete
   */
  where?: Prisma.KindWhereInput
  /**
   * Limit how many Kinds to delete.
   */
  limit?: number
}

/**
 * Kind without action
 */
export type KindDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kind
   */
  select?: Prisma.KindSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kind
   */
  omit?: Prisma.KindOmit<ExtArgs> | null
}
